# -*- coding: utf-8 -*-
"""srt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gCvcNPPbt3yEtIXjPnuHZ_MUSSkbeGfY
"""

!pip install openai
import openai
openai.api_key = 'sk-你的金鑰'

from google.colab import files
uploaded = files.upload()

with open('錄製6.wav', 'rb') as audio_file:
  transcript = openai.audio.transcriptions.create(
    file=audio_file,
    model='whisper-1',
    response_format='srt'
  )

print(transcript)
with open('錄製6.srt', 'w') as srt_file:
  srt_file.write(transcript)

files.download('錄製6.srt')