# -*- coding: utf-8 -*-
"""stt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTjK3ETKK07KigoEkUvvnzaOdqsiI_Ox
"""

!pip install openai
import openai
openai.api_key = 'sk-你的金鑰' # 金鑰

from google.colab import files
uploaded = files.upload()

with open('speech.mp3', "rb") as audio_file:
  transcript = openai.audio.transcriptions.create(
    model='whisper-1',
    file=audio_file,
    response_format = 'text'
  )

print(transcript)