# -*- coding: utf-8 -*-
"""trans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15F7tVMqC354bPlh8-wxGdMHECCYmAoCs
"""

!pip install openai
import openai
openai.api_key = 'sk-你的金鑰' # 金鑰

from google.colab import files
uploaded = files.upload()

with open('speech.mp3', "rb") as audio_file:
  transcript = openai.audio.translations.create(
    model="whisper-1",
    file=audio_file,
    response_format = 'text'
  )
print(transcript)