# -*- coding: utf-8 -*-
"""tts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bPZr1q07QHSuHqcxPLLAJFHvfxRmuvMX
"""

!pip install openai
import openai
openai.api_key = 'sk-你的金鑰' # 金鑰
speech_file_path = 'speech.mp3'

response = openai.audio.speech.create(
  model='tts-1',
  voice='alloy',
  input='陽明山國家公園內有十餘條登山步道，是一日遊的好去處。'
)
response.write_to_file(speech_file_path)
print('存檔完成!')

!ls

from google.colab import files
files.download(speech_file_path)