# -*- coding: utf-8 -*-
"""v_chat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SfcoVQwMcX-7qd_IKBLcK0lRdVhSKUuI
"""

!pip install openai
!pip install gradio
import gradio as gr
import openai
openai.api_key = 'sk-你的金鑰' # 金鑰

def vchar(input):

  ask = openai.chat.completions.create(
    model='gpt-3.5-turbo',
    messages=[{'role':'user','content':input}],
  )
  ans = openai.audio.speech.create(
    model='tts-1',
    voice='alloy',
    input=ask.choices[0].message.content
  )

  ans.write_to_file('ans.mp3')
  return 'ans.mp3'

demo = gr.Interface(
      fn=vchar,
      inputs='text',
      outputs='audio',
      allow_flagging='never',
    )
demo.launch()